### PR TITLE
Introduce docker support

### PR DESCRIPTION
**Pull request by russjr08**
This PR adds in a `Dockerfile` and `docker-compose.yml` file for easily running the application in a Docker container. This is useful for those who chose to use Docker for their Lemmy installations, and thus might not already have Node.js and pnpm already installed.

I've also updated the `README` file to provide instructions on using this as well!

### CODE REVIEW

**Comment by RocketDerp** [comment]
My repository is a fork off the mail, you should pull request to the LemmyNet main repo...

**Comment by russjr08** [comment]
That's odd, GitHub doesn't seem to list the general fork banner for some reason then, and I originally was linked to this repo from a Lemmy post. 

My apologies then, I'll try to track down the right repo and submit it there then, thanks!

**Comment by RocketDerp** [comment]
Ohh geesh, I'm sorry, I confused which repro this is.

You are helping with lemmy-helper? I thought this was the lemmy-docs form I was working on.

You are in the right place, let me read this again. My brain isn't keeping up with all the topic floating in it.

**Comment by RocketDerp** [comment]
Can we re-open this, what do I need to do?

**Comment by russjr08** [comment]
Ah, thank you! 😁

**Pull request merged**
